module.exports={
	
	siteRoot : "/opt/htdocs/cmsv3/cmsroot/sites/",
	sites:{
		"dsg.woniu.com"       : "dsg",
		"yh.woniu.com"        : "yh.woniu.com",
		"xzh.woniu.com"       : "xzh.woniu.com",
		"m.xzh.woniu.com"     : "xzh.woniu.com/m",
		"www.woniu.com"       : "woniu.com",
		"m.woniu.com"         : "woniu.com/m",
		"www.nextqueen.com"   : "www.nextqueen.com",
		"m.nextqueen.com"     : "www.nextqueen.com/m",
		"union.woniu.com"     : "union.woniu.com",
		"sanguo.woniu.com"    : "sanguo.woniu.com",
		"m.sanguo.woniu.com"  : "sanguo.woniu.com/m",
		"tzsy.woniu.com"      : "tzsy.woniu.com",
		"m.tzsy.woniu.com"    : "tzsy.woniu.com/m",
		"qe.woniu.com"        : "qe",
		"mm.woniu.com"        : "mm",
		"panda.woniu.com"     : "panda.woniu.com",
		"m.panda.woniu.com"   : "panda.woniu.com/m",
		"panda2.woniu.com"    : "panda2.woniu.com",
		"m.panda2.woniu.com"  : "panda2.woniu.com/m",
		"mj.woniu.com"        : "mj",
		"m.mj.woniu.com"      : "mj/m",
		"lz.woniu.com"        : "lz",
		"m.lz.woniu.com"      : "lz/m",
		"hj.woniu.com"        : "hj",
		"hero2.woniu.com"     : "hero2",
		"m.hero2.woniu.com"   : "hero2/m",
		"heart.woniu.com"     : "heart.woniu.com",
		"m.heart.woniu.com"   : "heart.woniu.com/m",
		"gyc.woniu.com"       : "gyc.woniu.com",
		"m.gyc.woniu.com"     : "gyc.woniu.com/m",
		"feicui.woniu.com"    : "feicui.woniu.com",
		"dsg.woniu.com"       : "dsg",
		"dragon.woniu.com"    : "dragon.woniu.com",
		"m.dragon.woniu.com"  : "dragon.woniu.com/m",
		"ty.woniu.com"        : "tyfb",
		"tzsy.woniu.com"      : "tzsy.woniu.com",
		"m.tzsy.woniu.com"    : "tzsy.woniu.com/m",
		"dhh.woniu.com"       : "dhh",
		"ddp.woniu.com"       : "ddp.woniu.com",
		"cj.woniu.com"        : "cj.woniu.com",
		"m.cj.woniu.com"      : "cj.woniu.com/m",
		"app.woniu.com"       : "app.woniu.com",
		"9yinsy.woniu.com"    : "9yinsy.woniu.com",  
		"m.9yinsy.woniu.com"  : "9yinsy.woniu.com/m",
		"9yindp.woniu.com"    : "9yindp.woniu.com",
		"m.9yindp.woniu.com"  : "9yindp.woniu.com/m",
		"9yin.woniu.com"      : "9yin",
		"m.ddp.woniu.com"     : "ddp.woniu.com/m",
		"9yangsy.woniu.com"   : "9yangsy.woniu.com",
		"m.9yangsy.woniu.com" : "9yangsy.woniu.com/m",
		"9yang.woniu.com"     : "9yang.woniu.com",
		"cps.woniu.com"       : "cps.woniu.com"
	}
}